package com.blue.dal.entity;

import java.util.Date;

public class UserBoot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.id
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.pid
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.user_name
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.authority
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    private String authority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.role
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.age
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column boot_user.create_date
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.id
     *
     * @return the value of boot_user.id
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.id
     *
     * @param id the value for boot_user.id
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.pid
     *
     * @return the value of boot_user.pid
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.pid
     *
     * @param pid the value for boot_user.pid
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.user_name
     *
     * @return the value of boot_user.user_name
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.user_name
     *
     * @param userName the value for boot_user.user_name
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.authority
     *
     * @return the value of boot_user.authority
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.authority
     *
     * @param authority the value for boot_user.authority
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    public void setAuthority(String authority) {
        this.authority = authority == null ? null : authority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.role
     *
     * @return the value of boot_user.role
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.role
     *
     * @param role the value for boot_user.role
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.age
     *
     * @return the value of boot_user.age
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.age
     *
     * @param age the value for boot_user.age
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column boot_user.create_date
     *
     * @return the value of boot_user.create_date
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column boot_user.create_date
     *
     * @param createDate the value for boot_user.create_date
     *
     * @mbggenerated Sun Dec 22 11:20:07 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}