package com.blue.dal.entity;

import java.util.Date;

public class UserBoot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_boot.id
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_boot.pid
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_boot.salt
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_boot.password
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_boot.user_name
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_boot.authority
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    private String authority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_boot.role
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_boot.age
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_boot.create_date
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_boot.id
     *
     * @return the value of tb_user_boot.id
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_boot.id
     *
     * @param id the value for tb_user_boot.id
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_boot.pid
     *
     * @return the value of tb_user_boot.pid
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_boot.pid
     *
     * @param pid the value for tb_user_boot.pid
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_boot.salt
     *
     * @return the value of tb_user_boot.salt
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_boot.salt
     *
     * @param salt the value for tb_user_boot.salt
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_boot.password
     *
     * @return the value of tb_user_boot.password
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_boot.password
     *
     * @param password the value for tb_user_boot.password
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_boot.user_name
     *
     * @return the value of tb_user_boot.user_name
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_boot.user_name
     *
     * @param userName the value for tb_user_boot.user_name
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_boot.authority
     *
     * @return the value of tb_user_boot.authority
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_boot.authority
     *
     * @param authority the value for tb_user_boot.authority
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public void setAuthority(String authority) {
        this.authority = authority == null ? null : authority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_boot.role
     *
     * @return the value of tb_user_boot.role
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_boot.role
     *
     * @param role the value for tb_user_boot.role
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_boot.age
     *
     * @return the value of tb_user_boot.age
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_boot.age
     *
     * @param age the value for tb_user_boot.age
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_boot.create_date
     *
     * @return the value of tb_user_boot.create_date
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_boot.create_date
     *
     * @param createDate the value for tb_user_boot.create_date
     *
     * @mbggenerated Sat Jan 18 10:56:54 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}